name: Daily Pull

on:
  schedule:
    - cron: '0 12 * * *' # Run once every day.
  workflow_dispatch: # Allow manual workflow run as well.
    
jobs:
  daily-pull-job:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Mercurial from Ubuntu's repository
    - name: Install Mercurial
      run: sudo apt-get update && sudo apt-get install -y mercurial

    # Switch to branch 'tb' and pull from hg
    - name: Pull from hg to branch
      run: |
        # git config user.name
        # git config user.email
        echo "Present Work Dir: "
        pwd 
        git config user.email "githubWorkflow@githubActions.com"
        git config user.name "githubActionsUser"
        git fetch
        if ! git rev-parse --verify tb >/dev/null 2>&1; then
          git checkout -b tb
        else
          git checkout tb
        fi
        git checkout tb # we should be already in here by now.
        /usr/bin/hg clone https://hg.mozilla.org/mozilla-central source/
        cd source/
        /usr/bin/hg clone https://hg.mozilla.org/comm-central comm/
        cd ..
        git add .
        git commit -m "Daily sync from tb-hg on $(date)" --no-edit
        git push -u origin tb
      #working-directory: tb-desktop
      env:
          GITHUB_TOKEN: ${{ secrets.GTHB_TKN }}

        
