name: Daily Pull

on:
  schedule:
    - cron: '25 6 * * *' # Run once every day.
    
jobs:
  daily-pull-job:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Mercurial from Ubuntu's repository
    - name: Install Mercurial
      run: sudo apt-get update && sudo apt-get install -y mercurial

    # Switch to branch 'tb' and pull from hg
    - name: Switch to branch 'tb'
      run: |
        git checkout -B tb
        hg clone https://hg.mozilla.org/mozilla-central source/
        cd source/
        hg clone https://hg.mozilla.org/comm-central comm/
        git add .
        git commit -m "Daily sync" --no-edit

