name: Manual Trigger Workflow

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Example Step
        run: echo "Manually triggered workflow!"
